module.exports = {
  apps: [
    {
      name: "prime-finder-omp8",
      script: "./prime_finder_omp8",
      cwd: __dirname,
      env: {
        OMP_NUM_THREADS: "8",
      },
      args: "--target-digits 1000",
      out_file: "./logs/prime-finder-omp8.log",
      error_file: "./logs/prime-finder-omp8.error.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      autorestart: false,
    },
    {
      name: "prime-finder-omp16",
      script: "./prime_finder_omp16",
      cwd: __dirname,
      env: {
        OMP_NUM_THREADS: "16",
      },
      args: "--target-digits 1000",
      out_file: "./logs/prime-finder-omp16.log",
      error_file: "./logs/prime-finder-omp16.error.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      autorestart: false,
    },
    {
      name: "prime-finder-omp32",
      script: "./prime_finder_omp32",
      cwd: __dirname,
      env: {
        OMP_NUM_THREADS: "32",
      },
      args: "--target-digits 10000",
      out_file: "./logs/prime-finder-omp32.log",
      error_file: "./logs/prime-finder-omp32.error.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      autorestart: false,
    },
    {
      name: "prime-finder-omp64",
      script: "./prime_finder_omp64",
      cwd: __dirname,
      env: {
        OMP_NUM_THREADS: "64",
      },
      args: "--target-digits 30000 --flo_predict 1",
      out_file: "./logs/prime-finder-omp64.log",
      error_file: "./logs/prime-finder-omp64.error.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      autorestart: false,
    },
    {
      name: "prime-finder-omp192",
      script: "./prime_finder_omp192",
      cwd: __dirname,
      env: {
        OMP_NUM_THREADS: "192",
      },
      args: "--target-digits 100000 --flo_predict 1",
      out_file: "./logs/prime-finder-omp64.log",
      error_file: "./logs/prime-finder-omp64.error.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      autorestart: false,
    },
  ],
};
